version: 2.1
orbs:
  cloudsmith: pagerduty/cloudsmith@1.0.5

jobs:
  build:
    docker:
      - image: cimg/node:18.12.1
    executor: cloudsmith/default
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt install pip3
      - run:
          name: Set Environment Variables
          command: |
            echo "export NPM_TOKEN=${CLOUDSMITH_NPM_TOKEN}" >> "$BASH_ENV"
            source "$BASH_ENV"

      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run:
          command: npm test
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'
      - run: npm run check-typescript
      - run:
          name: dependency audit
          command: ./scripts/better-audit.sh
      - run:
          name: packaging test
          command: ./scripts/packaging-test.sh
      - persist_to_workspace:
          root: .
          paths:
            - lib
            - node_modules
  publish:
    docker:
      - image: cimg/node:18.12.1
    executor: cloudsmith/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - cloudsmith/ensure-api-key
      - cloudsmith/install-cli
      - run:
          name: Set Environment Variables
          command: |
            echo "export NPM_TOKEN=${CLOUDSMITH_NPM_TOKEN}" >> "$BASH_ENV"
            source "$BASH_ENV"

      - run: npm version --no-git-tag-version $CIRCLE_TAG
      - run: npm pack --pack-destination dist/
      - cloudsmith/publish:
          cloudsmith-repository: pagerduty/npm
          package-path: dist/*
          package-format: npm

workflows:
  version: 2
  package:
    jobs:
      - build:
          context:
            - PagerDuty
            - Cloudsmith
          filters: # required since `publish` has tag filters AND requires `build`
            tags:
              only: /.*/
      - publish:
          context:
            - PagerDuty
            - Cloudsmith
          requires:
            - build
          filters:
            tags:
              only: /^[0-9].+/
            branches:
              ignore: /.*/
